### ISSUE TITLE
EXC_BAD_ACCESS in pj_init

### ISSUE THREAD

**Issue by TFreudi1** [jdiehl/libproj-ios#1]
I know it is a kind of old but you may have a tip.
I use latest Xcode, your script pull 4.8.0 proj4 from git, Lib's compile fine. Than I put it into simple project which also compile and link fine, but when I run it on simulator or iPhone I got an EXC_BAD_ACCESS (code=2) in pj_init_plus. I also have an very old version of a proj4 lib which work when I use it instead.
 
NSString* proj4String = @"+proj=latlong +ellps=WGS84";
projPJ pj_merc = pj_init_plus([proj4String UTF8String])) ); // Here the Exception throws

**Comment by jdiehl** [comment]
I just tested it with the latest version on my machine and everything works fine.

I think the issue you experience might be related to how memory management works across C and Objective-C. Please try using a C-String instead of an Objective-C string and see if that solves your issue:

```
pj_init_plus("+proj=latlong +ellps=WGS84");
```

You can debug these kinds of exceptions by running Instruments (CMD-I) and selecting "Zombies".

**Comment by TFreudi1** [comment]
Sorry I had holiday a few days I started with simple c Strings, because I thought it may have something to do with these I tried NSString
![bildschirmfoto 2017-06-01 um 17 38 52](https://cloud.githubusercontent.com/assets/4739177/26687938/86dc13cc-46f1-11e7-8d34-233d931eabba.png)

What should CMD-i Zombies should show me?I see a lot of allocations. Build your lib without errors and then let Xcode generate a new single view iOS App and put the pj_init code inside viewDidLoad.

**Comment by jdiehl** [comment]
The Zombies command tells you when the runtime is trying to access an Objective-C object that has been released, which is often the reason for bad access errors.

**Comment by TFreudi1** [comment]
I dont know how the Zombies should help I saw nothing interesting in that output, the last 3 rows shows pj_malloc then a lot of internal allocations but no error line or something. You wrote you tested it on your machine, did you build an iOS App ? Or a Mac App?

**Comment by jdiehl** [comment]
I compiled and ran an app using the library on an iOS device. Zombies was just a guess, if it didn't work I don't know how to help you further.

**Comment by TFreudi1** [comment]
Ok thank you for your help, I thought it is something simple, like you add a linker or compiler switch to your iOS App or you use a Mac App.
